services:
  YesPlayMusic:
    build:
      context: .
    image: yesplaymusic
    container_name: YesPlayMusic
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    expose:
      - 80
    restart: always
